<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <RootNamespace>QuarrelEx</RootNamespace>
    <AssemblyName>QuarrelEx</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>1.1.7</Version>
    <FileVersion>1.1.7.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Update="Data\BattleCityEx.ini" CopyToOutputDirectory="PreserveNewest" />
    <None Update="Help\Help_zh-CN.txt" CopyToOutputDirectory="PreserveNewest" />
    <None Update="Help\Help_en-US.txt" CopyToOutputDirectory="PreserveNewest" />
    <None Update="Help\TSA_Help_zh-CN.txt" CopyToOutputDirectory="PreserveNewest" />
    <None Update="Help\TSA_Help_en-US.txt" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
