#!/usr/bin/env python3
"""Generate the Desktop compile-time localization payload from /locales.

The JSON files remain the canonical translation source.  The generated C# file
makes Desktop language switching independent of loose Locales files at runtime.
"""
from pathlib import Path
import base64, gzip, hashlib, json

ROOT = Path(__file__).resolve().parents[1]
LOC = ROOT / "locales"
OUT = ROOT / "desktop" / "QuarrelEx" / "Localization" / "BuiltInCatalogs.g.cs"
NAMES = ("source-keys", "zh-CN", "en-US", "ja-JP")

rows = []
for name in NAMES:
    path = LOC / f"{name}.json"
    raw = path.read_bytes()
    packed = base64.b64encode(gzip.compress(raw, compresslevel=9, mtime=0)).decode("ascii")
    chunks = [packed[i:i+120] for i in range(0, len(packed), 120)]
    expr = " +\n            ".join(json.dumps(chunk) for chunk in chunks)
    rows.append((path.name, expr, hashlib.sha256(raw).hexdigest(), len(raw)))

lines = [
    "// <auto-generated>",
    "// Generated from /locales by tools/generate_desktop_i18n.py.",
    "// Do not edit this file directly; edit the JSON catalogs and regenerate.",
    "// </auto-generated>",
    "using System.IO.Compression;",
    "using System.Text;",
    "",
    "namespace QuarrelEx.Localization;",
    "",
    "internal static class BuiltInCatalogs",
    "{",
    "    private static readonly IReadOnlyDictionary<string, string> Payloads = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)",
    "    {",
]
for filename, expr, sha, size in rows:
    lines += [
        f"        // {filename}: {size} bytes, SHA256 {sha}",
        f"        [{json.dumps(filename)}] = {expr},",
    ]
lines += [
    "    };",
    "",
    "    internal static string? ReadJson(string fileName)",
    "    {",
    "        if (!Payloads.TryGetValue(fileName, out var payload)) return null;",
    "        try",
    "        {",
    "            var compressed = Convert.FromBase64String(payload);",
    "            using var input = new MemoryStream(compressed, writable: false);",
    "            using var gzip = new GZipStream(input, CompressionMode.Decompress);",
    "            using var reader = new StreamReader(gzip, Encoding.UTF8, detectEncodingFromByteOrderMarks: true);",
    "            return reader.ReadToEnd();",
    "        }",
    "        catch",
    "        {",
    "            return null;",
    "        }",
    "    }",
    "}",
]
OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"Generated {OUT.relative_to(ROOT)}")
